baseURL: "/"
title: Best Kayak to Buy
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Best Kayak to Buy
  description: "Welcome to [Best Kayak To Buy](https://bestkayaktobuy.com).  Discover the very best quality kayaks and read our honest expert reviews."
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: light # dark, light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Best Kayak To Buy"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: this is a title
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi Welcome to Best Kayak To Buy"
    Content: Welcome to my [Best Kayak To Buy](https://bestkayaktobuy.com). On this website we review the best kayaks available and give our honest opinion on how good they are.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: instagram
      url: "https://instagram.com/"
    - name: youtube
      url: "https://youtube.com/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: home
      name: Home
      url: https://bestkayaktobuy.com
      weight: 10
    - identifier: Brands
      name: Brands
      url: /categories/
      weight: 20
    - identifier: Affiliate Disclosure
      name: Affiliate Disclosure
      url: /affiliate-disclosure/
      weight: 40
    - identifier: Buying Guides
      name: Buying Guides
      url: /tags/buying-guides/
      weight: 30
    - identifier: Privacy Policy
      name: Privacy Policy
      url: /privacy-policy/
      weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
    - markup:
        highlight:
        anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: monokai
